CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Categories" (
    "Id" bigint NOT NULL,
    "Name" text NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Departments" (
    "Id" bigint NOT NULL,
    "Name" text NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE "Documents" (
    "Id" bigint NOT NULL,
    "Title" text NULL,
    "DepartmentId" bigint NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DocumentCategory" (
    "DocumentId" bigint NOT NULL,
    "CategoryId" bigint NOT NULL,
    CONSTRAINT "PK_DocumentCategory" PRIMARY KEY ("DocumentId", "CategoryId"),
    CONSTRAINT "FK_DocumentCategory_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentCategory_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DocumentCategory_CategoryId" ON "DocumentCategory" ("CategoryId");

CREATE INDEX "IX_Documents_DepartmentId" ON "Documents" ("DepartmentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181215184556_documentMigrations', '2.2.0-rtm-35687');

ALTER TABLE "Documents" ADD code text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181215191952_documentMigrations2', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181215220354_teste', '2.2.0-rtm-35687');

ALTER TABLE "Documents" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Documents" ALTER COLUMN "Id" SET NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Departments" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Departments" ALTER COLUMN "Id" SET NOT NULL;
ALTER TABLE "Departments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Categories" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Categories" ALTER COLUMN "Id" SET NOT NULL;
ALTER TABLE "Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181216200346_doc1', '2.2.0-rtm-35687');

ALTER TABLE "Documents" RENAME COLUMN code TO "Code";

ALTER TABLE "Documents" ALTER COLUMN "Code" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Code" SET NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Code" DROP DEFAULT;

ALTER TABLE "Documents" ALTER COLUMN "Title" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Title" SET NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Title" DROP DEFAULT;

ALTER TABLE "Departments" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Departments" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Departments" ALTER COLUMN "Name" DROP DEFAULT;

ALTER TABLE "Categories" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Categories" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Categories" ALTER COLUMN "Name" DROP DEFAULT;

CREATE UNIQUE INDEX "IX_Documents_Code" ON "Documents" ("Code");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181217230801_doc17', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181217231829_doc17.2', '2.2.0-rtm-35687');

ALTER TABLE "Documents" DROP CONSTRAINT "FK_Documents_Departments_DepartmentId";

DROP TABLE "DocumentCategory";

ALTER TABLE "Documents" RENAME COLUMN "DepartmentId" TO "CategoryId";

ALTER INDEX "IX_Documents_DepartmentId" RENAME TO "IX_Documents_CategoryId";

CREATE TABLE "DocumentDepartment" (
    "DocumentId" bigint NOT NULL,
    "DepartmentId" bigint NOT NULL,
    CONSTRAINT "PK_DocumentDepartment" PRIMARY KEY ("DocumentId", "DepartmentId"),
    CONSTRAINT "FK_DocumentDepartment_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentDepartment_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DocumentDepartment_DepartmentId" ON "DocumentDepartment" ("DepartmentId");

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181218013148_docc18', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181221151438_migrationFinale', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181222014414_teste2', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181222014534_teste3', '2.2.0-rtm-35687');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181222014705_teste4', '2.2.0-rtm-35687');

ALTER TABLE "Documents" ALTER COLUMN "Title" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Title" DROP NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Title" DROP DEFAULT;

ALTER TABLE "Documents" ALTER COLUMN "Code" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Code" DROP NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Code" DROP DEFAULT;

ALTER TABLE "Departments" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Departments" ALTER COLUMN "Name" DROP NOT NULL;
ALTER TABLE "Departments" ALTER COLUMN "Name" DROP DEFAULT;

ALTER TABLE "Categories" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Categories" ALTER COLUMN "Name" DROP NOT NULL;
ALTER TABLE "Categories" ALTER COLUMN "Name" DROP DEFAULT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181222014832_teste5', '2.2.0-rtm-35687');

ALTER TABLE "Documents" ALTER COLUMN "Title" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Title" SET NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Title" DROP DEFAULT;

ALTER TABLE "Documents" ALTER COLUMN "Code" TYPE text;
ALTER TABLE "Documents" ALTER COLUMN "Code" SET NOT NULL;
ALTER TABLE "Documents" ALTER COLUMN "Code" DROP DEFAULT;

ALTER TABLE "Departments" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Departments" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Departments" ALTER COLUMN "Name" DROP DEFAULT;

ALTER TABLE "Categories" ALTER COLUMN "Name" TYPE text;
ALTER TABLE "Categories" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Categories" ALTER COLUMN "Name" DROP DEFAULT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20181222015256_teste6', '2.2.0-rtm-35687');

